services:
    test-suite-verify-conditions:
        build: .
        command: npx mocha 'tst/integ/verifyConditions.test.js'
        depends_on:
            - mock-registry

    test-suite-prepare-publish:
        build: .
        command: npx mocha 'tst/integ/preparePublish.test.js'
        depends_on:
            - mock-registry

    mock-registry:
        image: registry:2.8.3
